#!/bin/sh

#
#  Creates a raw Dirac sequence from raw YUV pictures.
#
TESTPATH=$HOME/test
GST=gst-launch-0.10 
input=${TESTPATH}/vic.ogg
#output=${TESTPATH}/vic_out.avi
#GSTD="--gst-debug-no-color --gst-debug-level=5 --gst-plugin-spew"
#taskset -c 2 
#${GST} ${GSTD} -v filesrc location=$input  \
#	! decodebin \
#	! avimux ! filesink location=$output

output=${TESTPATH}/vic_out2.yuv
taskset -c 0 ${GST} ${GSTD} -v filesrc location=$input  \
	! decodebin \
	! filesink location=$output

