#!/bin/sh

mediadir=/home/ds/media

all="SD-default SD-VBR-10dB SD-VBR-20dB SD-VBR-30dB SD-VBR-40dB \
    SD-CBR-250kb SD-CBR-500kb \
    SD-CBR-1Mb SD-CBR-2Mb SD-LD-40Mb SD-LD-10Mb SD-lossless SD-intra-only"

list="$all"
#list=SD-default

extraopts=""

trap exit INT

get_profile() {
  case $1 in
    SD-default) schroopts="" ;;
    SD-VBR-10dB) schroopts="rate-control=0 noise-threshold=10" ;;
    SD-VBR-20dB) schroopts="rate-control=0 noise-threshold=20" ;;
    SD-VBR-30dB) schroopts="rate-control=0 noise-threshold=30" ;;
    SD-VBR-40dB) schroopts="rate-control=0 noise-threshold=40" ;;
    SD-CBR-250kb) schroopts="rate-control=1 bitrate=250000" ;;
    SD-CBR-500kb) schroopts="rate-control=1 bitrate=500000" ;;
    SD-CBR-1Mb) schroopts="rate-control=1 bitrate=1000000" ;;
    SD-CBR-2Mb) schroopts="rate-control=1 bitrate=2000000" ;;
    SD-LD-40Mb) schroopts="rate-control=2 bitrate=41472000 intra-wavelet=1" ;;
    SD-LD-20Mb) schroopts="rate-control=2 bitrate=20736000 intra-wavelet=1" ;;
    SD-LD-10Mb) schroopts="rate-control=2 bitrate=10368000 intra-wavelet=1" ;;
    SD-lossless) schroopts="rate-control=3" ;;
    SD-intra-only) schroopts="gop-structure=1" ;;
  esac
}

encode() {
  # engine3
  get_profile $prof
  output=$file.$prof.drc
  gst-launch-0.10 videotestsrc num-buffers=300 ! \
    cairotimeoverlay ! \
    cairotextoverlay text="$prof" halign=left deltay=-100 ! \
    ffmpegcolorspace ! \
    video/x-raw-yuv,format=\(fourcc\)"UYVY",width=$width,height=$height,framerate=$framerate,pixel-aspect-ratio=$par ! \
    ffmpegcolorspace ! \
    schroenc $schroopts $extraopts ! \
    filesink location=$output
}

encode_all() {
  input=$mediadir/$subdir/$file.yuv
  size=$(($height*$width*2))

  for each in $list
  do
    prof=$each
    encode
  done
}


height=480
width=720
par=10/11
framerate=30/1
file=vts

encode_all

