#!/bin/sh

mediadir=/home/ds/media

all="SD-default SD-VBR-10dB SD-VBR-20dB SD-VBR-30dB SD-VBR-40dB \
    SD-CBR-250kb SD-CBR-500kb SD-CBR-1Mb SD-CBR-2Mb SD-CBR-3Mb \
    SD-LD-40Mb SD-LD-10Mb SD-lossless SD-intra-only SD-tworef \
    SD-intra-noarith"

list="$all"

#list=SD-tworef
list=SD-CBR-49Mb-intra
list=SD-CBR-49Mb-intra-noarith

#extraopts="enable-phasecorr-estimation=true enable-hierarchical-estimation=false"
#extraopts="perceptual-weighting=1"
extraopts="enable-psnr=true"

trap exit INT

get_profile() {
  case $1 in
    SD-default) schroopts="" ;;
    SD-VBR-10dB) schroopts="rate-control=0 noise-threshold=10" ;;
    SD-VBR-20dB) schroopts="rate-control=0 noise-threshold=20" ;;
    SD-VBR-30dB) schroopts="rate-control=0 noise-threshold=30" ;;
    SD-VBR-40dB) schroopts="rate-control=0 noise-threshold=40" ;;
    SD-CBR-250kb) schroopts="rate-control=1 bitrate=250000" ;;
    SD-CBR-500kb) schroopts="rate-control=1 bitrate=500000" ;;
    SD-CBR-1Mb) schroopts="rate-control=1 bitrate=1000000" ;;
    SD-CBR-2Mb) schroopts="rate-control=1 bitrate=2000000" ;;
    SD-CBR-3Mb) schroopts="rate-control=1 bitrate=3000000" ;;
    SD-LD-40Mb) schroopts="rate-control=2 bitrate=41472000" ;;
    SD-LD-20Mb) schroopts="rate-control=2 bitrate=20736000" ;;
    SD-LD-10Mb) schroopts="rate-control=2 bitrate=10368000" ;;
    SD-CBR-25Mb-intra-noarith) schroopts="rate-control=1 gop-structure=1 bitrate=24883200 enable_noarith=1" ;;
    SD-CBR-25Mb-intra) schroopts="rate-control=1 gop-structure=1 bitrate=24883200" ;;
    SD-CBR-41Mb-intra-noarith) schroopts="rate-control=1 gop-structure=1 bitrate=41472000 enable_noarith=1" ;;
    SD-CBR-41Mb-intra) schroopts="rate-control=1 gop-structure=1 bitrate=41472000" ;;
    SD-CBR-49Mb-intra-noarith) schroopts="rate-control=1 gop-structure=1 bitrate=49766400 enable_noarith=1" ;;
    SD-CBR-49Mb-intra) schroopts="rate-control=1 gop-structure=1 bitrate=49766400" ;;
    SD-lossless) schroopts="rate-control=3" ;;
    SD-intra-only) schroopts="gop-structure=1" ;;
    SD-intra-noarith) schroopts="gop-structure=1 enable_noarith=1" ;;
    SD-tworef) schroopts="gop-structure=4" ;;
  esac
}

encode() {
  # engine3
  get_profile $prof
  output=$file.$prof.drc
  echo "encoding $name using $prof"
  gst-launch-0.10 filesrc location=$input blocksize=$size ! \
    video/x-raw-yuv,format=\(fourcc\)"UYVY",width=$width,height=$height,framerate=$framerate,pixel-aspect-ratio=$par ! \
    ffmpegcolorspace ! \
    schroenc $schroopts $extraopts ! \
    filesink location=$output
}

encode_all() {
  input=$mediadir/$subdir/$file.yuv
  size=$(($height*$width*2))

  for each in $list
  do
    prof=$each
    encode
  done
}



subdir=VQEG/SDTV/ANSI_T1_801_01
height=486
width=720
par=10/11
framerate=30000/1001

file=washdc
#encode_all
file=ysmite
#encode_all

subdir=VQEG/SDTV/VQEG_Phase1/TestSequences/Reference
height=486
width=720
par=10/11
framerate=30000/1001

file=src20_ref__525
encode_all

height=576
width=720
par=12/11
framerate=25/1
file=src1_ref__625
#encode_all
file=src2_ref__625
#encode_all
file=src3_ref__625
#encode_all
file=src4_ref__625
#encode_all
file=src5_ref__625
#encode_all
file=src6_ref__625
#encode_all
file=src7_ref__625
#encode_all
file=src8_ref__625
#encode_all
file=src9_ref__625
#encode_all
file=src10_ref__625
#encode_all

height=486
width=720
par=10/11
framerate=30000/1001
file=src13_ref__525
#encode_all
file=src14_ref__525
#encode_all
file=src15_ref__525
#encode_all
file=src16_ref__525
#encode_all
file=src17_ref__525
#encode_all

