#!/usr/bin/env python
# -*- Mode: Python -*-
# vi:si:et:sw=4:sts=4:ts=4

#infile="showreel-short.SD-master.drc"
infile="showreel.SD-master.drc"
outfile="test.drc"

mediadir="/home/ds/media/masters"

import sys
import os
import gobject
gobject.threads_init()
import pygst
pygst.require('0.10')
import gst
import Numeric;

from test_encode import *;


def main(args):
    os.putenv("SCHRO_DUMP", "1");

    moo = EncodeTest();

    moo.set_input_file(mediadir + "/" + infile)
    moo.set_output_file(outfile)

    moo.set("rate-control", 1);
    moo.set("bitrate", 2500000);

    for each in args[1:]:
        (name,value) = each.split('=');
        value=float(value);
        moo.set(name,value);

    moo.go();

if __name__ == '__main__':
    sys.exit(main(sys.argv))

