#!/bin/sh

#file=elephants_dream
#file=showreel
#file=ants-1
file=testfootage
#file=bbb
#file=squirrel

mediadir=/home/ds/media/masters

all="SD-default SD-VBR-10dB SD-VBR-20dB SD-VBR-30dB SD-VBR-40dB \
    SD-CBR-250kb SD-CBR-500kb SD-CBR-1Mb SD-CBR-2Mb \
    SD-LD-40Mb SD-LD-10Mb SD-lossless SD-intra-only"

list="$all"

#list=HD720-Clam
#list=HD720-CBR-4Mb
#list=SIF-CBR-750kb
#list=SD-CBR-2Mb
#list=SD-default
list=HD720-Clam

extraopts=""
#extraopts="enable-bigblock-estimation=true enable-hierarchical-estimation=false"
#extraopts="$extraopts magic-mc-lambda=0.01"
#extraopts="$extraopts magic-mc-lambda=0.01"
#extraopts="$extraopts magic-error-power=4.0"
#extraopts="$extraopts perceptual-weighting=1 perceptual-distance=3.0"
#extraopts="$extraopts motion-block-overlap=3"
extraopts="$extraopts filtering=2 filter-value=1.0"
#extraopts="$extraopts intra-wavelet=1"
#extraopts="$extraopts inter-wavelet=0"
#extraopts="$extraopts transform-depth=3"
#extraopts="$extraopts motion-block-size=3"
#extraopts="$extraopts au-distance=100"
#extraopts="$extraopts magic-chroma-lambda-scale=0.1"
#extraopts="$extraopts magic-nonref-lambda-scale=0.03"
#extraopts="$extraopts magic-nonref-lambda-scale=0.00"
#extraopts="$extraopts magic-subband0-lambda-scale=1000.0"
#extraopts="$extraopts magic-subgroup-length=3"
#extraopts="$extraopts magic-block-search-threshold=100"
extraopts="$extraopts magic-scene-change-threshold=0.05"
#extraopts="$extraopts enable-md5=1"
export SCHRO_DUMP=1

#diracopts="qf=4"
diracopts="targetrate=4000"

trap exit INT

get_profile() {
  case $1 in
    SD-default) schroopts="" ;;
    SD-VBR-10dB) schroopts="rate-control=0 noise-threshold=10" ;;
    SD-VBR-20dB) schroopts="rate-control=0 noise-threshold=20" ;;
    SD-VBR-30dB) schroopts="rate-control=0 noise-threshold=30" ;;
    SD-VBR-40dB) schroopts="rate-control=0 noise-threshold=40" ;;
    SD-CBR-250kb) schroopts="rate-control=1 bitrate=250000" ;;
    SD-CBR-500kb) schroopts="rate-control=1 bitrate=500000" ;;
    SD-CBR-1Mb) schroopts="rate-control=1 bitrate=1000000" ;;
    SD-CBR-2Mb) schroopts="rate-control=1 bitrate=2000000" ;;
    SD-CBR-3Mb) schroopts="rate-control=1 bitrate=3000000" ;;
    SD-LD-40Mb) schroopts="rate-control=2 bitrate=41472000" ;;
    SD-LD-20Mb) schroopts="rate-control=2 bitrate=20736000" ;;
    SD-LD-10Mb) schroopts="rate-control=2 bitrate=10368000" ;;
    SD-lossless) schroopts="rate-control=3" ;;
    SD-intra-only) schroopts="gop-structure=1" ;;
    SD-tworef) schroopts="gop-structure=4" ;;
    HD720-tworef) schroopts="gop-structure=4" ;;
    HD720-CBR-3Mb) schroopts="rate-control=1 bitrate=3000000" ;;
    HD720-CBR-4Mb) schroopts="rate-control=1 bitrate=4500000" ;;
    HD720-CBR-5Mb) schroopts="rate-control=1 bitrate=5000000" ;;
    HD720-backref-CBR-5Mb) schroopts="gop-structure=2 rate-control=1 bitrate=5000000" ;;
    HD720-test) schroopts="rate-control=1 bitrate=2000000 au_distance=24" ;;
    HD720-intra) schroopts="gop-structure=1 rate-control=1 bitrate=10000000" ;;
    SD-CBR-3Mb-tworef) schroopts="rate-control=1 bitrate=3000000" ;;
    HD270-default) schroopts="" ;;
    SIF-CBR-750kb) schroopts="rate-control=1 bitrate=750000" ;;
    SD-Cerr) schroopts="rate-control=5" ;;
    HD720-Clam) schroopts="rate-control=4 magic-lambda=0.005" ;;
    HD720-Cerr) schroopts="rate-control=5 noise-threshold=20" ;;
    HD720-java) schroopts="gop-structure=1" ;;
  esac
  case $1 in
    SIF*) infile="$file.SIF-master.drc" ;;
    SD*) infile="$file.SD-master.drc" ;;
    HD720*) infile="$file.HD720-master.drc" ;;
    HD1080*) infile="$file.HD1080-master.drc" ;;
  esac
}

encode() {
  # engine3
  get_profile $prof
  #output=$file.$prof.$(date '+r%m%d%H%M').drc
  output=$file.$prof.$(date '+r%m%d%H%M').mpeg
  echo "encoding $file using $prof"

  gst-launch-0.10 filesrc location=$mediadir/$infile ! \
    schrodec ! \
    ffmpegcolorspace ! \
    video/x-raw-yuv,format=\(fourcc\)YUY2 ! \
    schroenc $schroopts $extraopts ! \
    filesink location=$output
  #>/dev/null 2>/dev/null
  #  diracenc $diracopts ! \
}

encode_all() {
  for each in $list
  do
    prof=$each
    encode
  done
}

encode_all

