#!/bin/sh

#file=elephants_dream
#file=showreel
file=squirrel

mediadir=/home/ds/media/masters

all="SD-default SD-VBR-10dB SD-VBR-20dB SD-VBR-30dB SD-VBR-40dB \
    SD-CBR-250kb SD-CBR-500kb SD-CBR-1Mb SD-CBR-2Mb \
    SD-LD-40Mb SD-LD-10Mb SD-lossless SD-intra-only"

list="$all"

#list=HD720-Clam
#list=HD720-CBR-4Mb
#list=SIF-CBR-750kb
list=SD-CBR-2Mb

#extraopts="enable-bigblock-estimation=true enable-hierarchical-estimation=false"
#extraopts="perceptual-weighting=1 magic-error-power=4.0 magic-mc-lambda=0.01"
#extraopts="perceptual-weighting=1"
#extraopts="motion-block-size=2"
extraopts=""
export SCHRO_DUMP=1

trap exit INT

function get_profile {
  case $1 in
    SD-default) schroopts="" ;;
    SD-VBR-10dB) schroopts="rate-control=0 noise-threshold=10" ;;
    SD-VBR-20dB) schroopts="rate-control=0 noise-threshold=20" ;;
    SD-VBR-30dB) schroopts="rate-control=0 noise-threshold=30" ;;
    SD-VBR-40dB) schroopts="rate-control=0 noise-threshold=40" ;;
    SD-CBR-250kb) schroopts="rate-control=1 bitrate=250000" ;;
    SD-CBR-500kb) schroopts="rate-control=1 bitrate=500000" ;;
    SD-CBR-1Mb) schroopts="rate-control=1 bitrate=1000000" ;;
    SD-CBR-2Mb) schroopts="rate-control=1 bitrate=2000000" ;;
    SD-CBR-3Mb) schroopts="rate-control=1 bitrate=3000000" ;;
    SD-LD-40Mb) schroopts="rate-control=2 bitrate=41472000" ;;
    SD-LD-20Mb) schroopts="rate-control=2 bitrate=20736000" ;;
    SD-LD-10Mb) schroopts="rate-control=2 bitrate=10368000" ;;
    SD-lossless) schroopts="rate-control=3" ;;
    SD-intra-only) schroopts="gop-structure=1" ;;
    SD-tworef) schroopts="gop-structure=4" ;;
    HD720-tworef) schroopts="gop-structure=4" ;;
    HD720-CBR-3Mb) schroopts="rate-control=1 bitrate=3000000" ;;
    HD720-CBR-4Mb) schroopts="rate-control=1 bitrate=4500000" ;;
    HD720-CBR-5Mb) schroopts="rate-control=1 bitrate=5000000" ;;
    HD720-backref-CBR-5Mb) schroopts="gop-structure=2 rate-control=1 bitrate=5000000" ;;
    HD720-test) schroopts="gop-structure=2 rate-control=1 bitrate=5000000 magic_inter_b_weight=0.0001" ;;
    HD720-intra) schroopts="gop-structure=1 rate-control=1 bitrate=10000000" ;;
    SD-CBR-3Mb-tworef) schroopts="rate-control=1 bitrate=3000000" ;;
    HD270-default) schroopts="" ;;
    SIF-CBR-750kb) schroopts="rate-control=1 bitrate=750000" ;;
    SD-Cerr) schroopts="rate-control=5" ;;
    HD720-Clam) schroopts="rate-control=4 magic-lambda=0.1" ;;
    HD720-Cerr) schroopts="rate-control=5 noise-threshold=20" ;;
  esac
  case $1 in
    SIF*) infile="$file.SIF-master.drc" ;;
    SD*) infile="$file.SD-master.drc" ;;
    HD720*) infile="$file.HD720-master.drc" ;;
    HD1080*) infile="$file.HD1080-master.drc" ;;
  esac
}

function encode {
  # engine3
  get_profile $prof
  output=$file.$prof.drc
  echo "encoding $file using $prof"

  gst-launch-0.10 filesrc location=$mediadir/$infile ! \
    schrodec ! \
    schroenc $schroopts $extraopts ! \
    filesink location=$output
  #>/dev/null 2>/dev/null
}

function encode_all {
  for each in $list
  do
    prof=$each
    encode
  done
}

encode_all

