
/* autogenerated from schro.orc */

#include <orc/orc.h>
#include <stdio.h>
#include <stdlib.h>
#include <schroedinger/schro.h>
#define MUTEX_LOCK() schro_mutex_lock (orc_mutex)
#define MUTEX_UNLOCK() schro_mutex_unlock (orc_mutex)
SchroMutex *orc_mutex;

#ifndef MUTEX_LOCK
#define MUTEX_LOCK do { } while (0)
#endif
#ifndef MUTEX_UNLOCK
#define MUTEX_UNLOCK do { } while (0)
#endif

#define ORC_CLAMP(x,a,b) ((x)<(a) ? (a) : ((x)>(b) ? (b) : (x)))
#define ORC_ABS(a) ((a)<0 ? (-a) : (a))
#define ORC_MIN(a,b) ((a)<(b) ? (a) : (b))
#define ORC_MAX(a,b) ((a)>(b) ? (a) : (b))
#define ORC_SB_MAX 127
#define ORC_SB_MIN (-1-ORC_SB_MAX)
#define ORC_UB_MAX 255
#define ORC_UB_MIN 0
#define ORC_SW_MAX 32767
#define ORC_SW_MIN (-1-ORC_SW_MAX)
#define ORC_UW_MAX 65535
#define ORC_UW_MIN 0
#define ORC_SL_MAX 2147483647
#define ORC_SL_MIN (-1-ORC_SL_MAX)
#define ORC_UL_MAX 4294967295U
#define ORC_UL_MIN 0
#define ORC_CLAMP_SB(x) ORC_CLAMP(x,ORC_SB_MIN,ORC_SB_MAX)
#define ORC_CLAMP_UB(x) ORC_CLAMP(x,ORC_UB_MIN,ORC_UB_MAX)
#define ORC_CLAMP_SW(x) ORC_CLAMP(x,ORC_SW_MIN,ORC_SW_MAX)
#define ORC_CLAMP_UW(x) ORC_CLAMP(x,ORC_UW_MIN,ORC_UW_MAX)
#define ORC_CLAMP_SL(x) ORC_CLAMP(x,ORC_SL_MIN,ORC_SL_MAX)
#define ORC_CLAMP_UL(x) ORC_CLAMP(x,ORC_UL_MIN,ORC_UL_MAX)
#define ORC_SWAP_W(x) ((((x)&0xff)<<8) | (((x)&0xff00)>>8))
#define ORC_SWAP_L(x) ((((x)&0xff)<<24) | (((x)&0xff00)<<8) | (((x)&0xff0000)>>8) | (((x)&0xff000000)>>24))


/* orc_add2_rshift_add_s16_22 */
static void
_backup_orc_add2_rshift_add_s16_22 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var16 = 2;
  const int16_t var17 = 2;
  int16_t var32;
  int16_t var33;
  int16_t var34;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var5[i];
    /* 1: addw */
    var33 = var32 + var16;
    /* 2: shrsw */
    var34 = var33 >> var17;
    /* 3: addw */
    var0[i] = var0[i] + var34;
  }

}

void
orc_add2_rshift_add_s16_22 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_add_s16_22");
      orc_program_set_backup_function (p, _backup_orc_add2_rshift_add_s16_22);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_constant (p, 2, 2, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_add2_rshift_sub_s16_22 */
static void
_backup_orc_add2_rshift_sub_s16_22 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var16 = 2;
  const int16_t var17 = 2;
  int16_t var32;
  int16_t var33;
  int16_t var34;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var5[i];
    /* 1: addw */
    var33 = var32 + var16;
    /* 2: shrsw */
    var34 = var33 >> var17;
    /* 3: subw */
    var0[i] = var0[i] - var34;
  }

}

void
orc_add2_rshift_sub_s16_22 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_sub_s16_22");
      orc_program_set_backup_function (p, _backup_orc_add2_rshift_sub_s16_22);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_constant (p, 2, 2, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_add2_rshift_add_s16_11 */
static void
_backup_orc_add2_rshift_add_s16_11 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: avgsw */
    var32 = (var4[i] + var5[i] + 1)>>1;
    /* 1: addw */
    var0[i] = var0[i] + var32;
  }

}

void
orc_add2_rshift_add_s16_11 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_add_s16_11");
      orc_program_set_backup_function (p, _backup_orc_add2_rshift_add_s16_11);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_add2_rshift_sub_s16_11 */
static void
_backup_orc_add2_rshift_sub_s16_11 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: avgsw */
    var32 = (var4[i] + var5[i] + 1)>>1;
    /* 1: subw */
    var0[i] = var0[i] - var32;
  }

}

void
orc_add2_rshift_sub_s16_11 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_sub_s16_11");
      orc_program_set_backup_function (p, _backup_orc_add2_rshift_sub_s16_11);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_add_const_rshift_s16_11 */
static void
_backup_orc_add_const_rshift_s16_11 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 1;
  const int16_t var17 = 1;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var16;
    /* 1: shrsw */
    var0[i] = var32 >> var17;
  }

}

void
orc_add_const_rshift_s16_11 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_const_rshift_s16_11");
      orc_program_set_backup_function (p, _backup_orc_add_const_rshift_s16_11);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 1, "c1");
      orc_program_add_constant (p, 2, 1, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_add_const_rshift_s16 */
static void
_backup_orc_add_const_rshift_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var0[i] + var24;
    /* 1: shrsw */
    var0[i] = var32 >> var25;
  }

}

void
orc_add_const_rshift_s16 (int16_t * d1, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_const_rshift_s16");
      orc_program_set_backup_function (p, _backup_orc_add_const_rshift_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_P1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_P2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_add_s16 */
static void
_backup_orc_add_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var0[i] = var4[i] + var5[i];
  }

}

void
orc_add_s16 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_s16");
      orc_program_set_backup_function (p, _backup_orc_add_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_addc_rshift_s16 */
static void
_backup_orc_addc_rshift_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var24 = ex->params[24];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var5[i];
    /* 1: shrsw */
    var0[i] = var32 >> var24;
  }

}

void
orc_addc_rshift_s16 (int16_t * d1, int16_t * s1, int16_t * s2, int p1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_addc_rshift_s16");
      orc_program_set_backup_function (p, _backup_orc_addc_rshift_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_P1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;

  orc_executor_run (ex);
}

/* orc_lshift1_s16 */
static void
_backup_orc_lshift1_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 1;

  for (i = 0; i < ex->n; i++) {
    /* 0: shlw */
    var0[i] = var4[i] << var16;
  }

}

void
orc_lshift1_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift1_s16");
      orc_program_set_backup_function (p, _backup_orc_lshift1_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 1, "c1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_lshift2_s16 */
static void
_backup_orc_lshift2_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 2;

  for (i = 0; i < ex->n; i++) {
    /* 0: shlw */
    var0[i] = var4[i] << var16;
  }

}

void
orc_lshift2_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift2_s16");
      orc_program_set_backup_function (p, _backup_orc_lshift2_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 2, "c1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_lshift_s16_ip */
static void
_backup_orc_lshift_s16_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var24 = ex->params[24];

  for (i = 0; i < ex->n; i++) {
    /* 0: shlw */
    var0[i] = var0[i] << var24;
  }

}

void
orc_lshift_s16_ip (int16_t * d1, int p1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift_s16_ip");
      orc_program_set_backup_function (p, _backup_orc_lshift_s16_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_P1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  orc_executor_run (ex);
}

/* orc_mas2_add_s16_ip */
static void
_backup_orc_mas2_add_s16_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var24 = ex->params[24];
  const int32_t var25 = ex->params[25];
  const int32_t var26 = ex->params[26];
  int16_t var32;
  int32_t var33;
  int32_t var34;
  int32_t var35;
  int16_t var36;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var5[i];
    /* 1: mulswl */
    var33 = var32 * var24;
    /* 2: addl */
    var34 = var33 + var25;
    /* 3: shrsl */
    var35 = var34 >> var26;
    /* 4: convlw */
    var36 = var35;
    /* 5: addw */
    var0[i] = var0[i] + var36;
  }

}

void
orc_mas2_add_s16_ip (int16_t * d1, int16_t * s1, int16_t * s2, int p1, int p2, int p3, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas2_add_s16_ip");
      orc_program_set_backup_function (p, _backup_orc_mas2_add_s16_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_parameter (p, 4, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "mulswl", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P2);
      orc_program_append (p, "shrsl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P3);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  orc_executor_run (ex);
}

/* orc_mas2_sub_s16_ip */
static void
_backup_orc_mas2_sub_s16_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var24 = ex->params[24];
  const int32_t var25 = ex->params[25];
  const int32_t var26 = ex->params[26];
  int16_t var32;
  int32_t var33;
  int32_t var34;
  int32_t var35;
  int16_t var36;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var5[i];
    /* 1: mulswl */
    var33 = var32 * var24;
    /* 2: addl */
    var34 = var33 + var25;
    /* 3: shrsl */
    var35 = var34 >> var26;
    /* 4: convlw */
    var36 = var35;
    /* 5: subw */
    var0[i] = var0[i] - var36;
  }

}

void
orc_mas2_sub_s16_ip (int16_t * d1, int16_t * s1, int16_t * s2, int p1, int p2, int p3, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas2_sub_s16_ip");
      orc_program_set_backup_function (p, _backup_orc_mas2_sub_s16_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_parameter (p, 4, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "mulswl", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P2);
      orc_program_append (p, "shrsl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P3);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  orc_executor_run (ex);
}

/* orc_mas4_across_add_s16_1991_ip */
static void
_backup_orc_mas4_across_add_s16_1991_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t * var6 = ex->arrays[6];
  const int16_t * var7 = ex->arrays[7];
  const int16_t var16 = 9;
  const int32_t var24 = ex->params[24];
  const int32_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int32_t var34;
  int32_t var35;
  int32_t var36;
  int32_t var37;
  int32_t var38;
  int16_t var39;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var5[i] + var6[i];
    /* 1: mulswl */
    var34 = var32 * var16;
    /* 2: addw */
    var33 = var4[i] + var7[i];
    /* 3: convswl */
    var35 = var33;
    /* 4: subl */
    var36 = var34 - var35;
    /* 5: addl */
    var37 = var36 + var24;
    /* 6: shrsl */
    var38 = var37 >> var25;
    /* 7: convlw */
    var39 = var38;
    /* 8: addw */
    var0[i] = var0[i] + var39;
  }

}

void
orc_mas4_across_add_s16_1991_ip (int16_t * d1, int16_t * s1, int16_t * s2, int16_t * s3, int16_t * s4, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas4_across_add_s16_1991_ip");
      orc_program_set_backup_function (p, _backup_orc_mas4_across_add_s16_1991_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_source (p, 2, "s3");
      orc_program_add_source (p, 2, "s4");
      orc_program_add_constant (p, 2, 9, "c1");
      orc_program_add_parameter (p, 4, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");
      orc_program_add_temporary (p, 4, "t4");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_S3);
      orc_program_append (p, "mulswl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_T2, ORC_VAR_S1, ORC_VAR_S4);
      orc_program_append (p, "convswl", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_T4);
      orc_program_append (p, "addl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "shrsl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;
  ex->arrays[ORC_VAR_S4] = s4;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_mas4_across_sub_s16_1991_ip */
static void
_backup_orc_mas4_across_sub_s16_1991_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t * var6 = ex->arrays[6];
  const int16_t * var7 = ex->arrays[7];
  const int16_t var16 = 9;
  const int32_t var24 = ex->params[24];
  const int32_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int32_t var34;
  int32_t var35;
  int32_t var36;
  int32_t var37;
  int32_t var38;
  int16_t var39;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var5[i] + var6[i];
    /* 1: mulswl */
    var34 = var32 * var16;
    /* 2: addw */
    var33 = var4[i] + var7[i];
    /* 3: convswl */
    var35 = var33;
    /* 4: subl */
    var36 = var34 - var35;
    /* 5: addl */
    var37 = var36 + var24;
    /* 6: shrsl */
    var38 = var37 >> var25;
    /* 7: convlw */
    var39 = var38;
    /* 8: subw */
    var0[i] = var0[i] - var39;
  }

}

void
orc_mas4_across_sub_s16_1991_ip (int16_t * d1, int16_t * s1, int16_t * s2, int16_t * s3, int16_t * s4, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas4_across_sub_s16_1991_ip");
      orc_program_set_backup_function (p, _backup_orc_mas4_across_sub_s16_1991_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_source (p, 2, "s3");
      orc_program_add_source (p, 2, "s4");
      orc_program_add_constant (p, 2, 9, "c1");
      orc_program_add_parameter (p, 4, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");
      orc_program_add_temporary (p, 4, "t4");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_S3);
      orc_program_append (p, "mulswl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_T2, ORC_VAR_S1, ORC_VAR_S4);
      orc_program_append (p, "convswl", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_T4);
      orc_program_append (p, "addl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "shrsl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;
  ex->arrays[ORC_VAR_S4] = s4;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_subtract_s16 */
static void
_backup_orc_subtract_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];

  for (i = 0; i < ex->n; i++) {
    /* 0: subw */
    var0[i] = var4[i] - var5[i];
  }

}

void
orc_subtract_s16 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_subtract_s16");
      orc_program_set_backup_function (p, _backup_orc_subtract_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_memcpy */
static void
_backup_orc_memcpy (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int8_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: copyb */
    var0[i] = var4[i];
  }

}

void
orc_memcpy (void * d1, void * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_memcpy");
      orc_program_set_backup_function (p, _backup_orc_memcpy);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 1, "s1");

      orc_program_append (p, "copyb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_add_s16_u8 */
static void
_backup_orc_add_s16_u8 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var5[i];
    /* 1: addw */
    var0[i] = var32 + var4[i];
  }

}

void
orc_add_s16_u8 (int16_t * d1, int16_t * s1, uint8_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_s16_u8");
      orc_program_set_backup_function (p, _backup_orc_add_s16_u8);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_S1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_convert_s16_u8 */
static void
_backup_orc_convert_s16_u8 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int8_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var0[i] = (uint8_t)var4[i];
  }

}

void
orc_convert_s16_u8 (uint16_t * d1, uint8_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_convert_s16_u8");
      orc_program_set_backup_function (p, _backup_orc_convert_s16_u8);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 1, "s1");

      orc_program_append (p, "convubw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_convert_u8_s16 */
static void
_backup_orc_convert_u8_s16 (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: convsuswb */
    var0[i] = ORC_CLAMP_UB(var4[i]);
  }

}

void
orc_convert_u8_s16 (uint8_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_convert_u8_s16");
      orc_program_set_backup_function (p, _backup_orc_convert_u8_s16);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "convsuswb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_offsetconvert_u8_s16 */
static void
_backup_orc_offsetconvert_u8_s16 (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 128;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var16;
    /* 1: convsuswb */
    var0[i] = ORC_CLAMP_UB(var32);
  }

}

void
orc_offsetconvert_u8_s16 (uint8_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_offsetconvert_u8_s16");
      orc_program_set_backup_function (p, _backup_orc_offsetconvert_u8_s16);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 128, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "convsuswb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_offsetconvert_s16_u8 */
static void
_backup_orc_offsetconvert_s16_u8 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int8_t * var4 = ex->arrays[4];
  const int16_t var16 = 128;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var4[i];
    /* 1: subw */
    var0[i] = var32 - var16;
  }

}

void
orc_offsetconvert_s16_u8 (int16_t * d1, uint8_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_offsetconvert_s16_u8");
      orc_program_set_backup_function (p, _backup_orc_offsetconvert_s16_u8);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_constant (p, 2, 128, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_subtract_s16_u8 */
static void
_backup_orc_subtract_s16_u8 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var5[i];
    /* 1: subw */
    var0[i] = var4[i] - var32;
  }

}

void
orc_subtract_s16_u8 (int16_t * d1, int16_t * s1, uint8_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_subtract_s16_u8");
      orc_program_set_backup_function (p, _backup_orc_subtract_s16_u8);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_multiply_and_add_s16_u8 */
static void
_backup_orc_multiply_and_add_s16_u8 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];
  int16_t var32;
  int16_t var33;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var5[i];
    /* 1: mullw */
    var33 = (var32 * var4[i]) & 0xffff;
    /* 2: addw */
    var0[i] = var0[i] + var33;
  }

}

void
orc_multiply_and_add_s16_u8 (int16_t * d1, int16_t * s1, uint8_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_multiply_and_add_s16_u8");
      orc_program_set_backup_function (p, _backup_orc_multiply_and_add_s16_u8);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_splat_s16_ns */
static void
_backup_orc_splat_s16_ns (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var24 = ex->params[24];

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var0[i] = var24;
  }

}

void
orc_splat_s16_ns (int16_t * d1, int p1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_splat_s16_ns");
      orc_program_set_backup_function (p, _backup_orc_splat_s16_ns);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");

      orc_program_append (p, "copyw", ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  orc_executor_run (ex);
}

/* orc_splat_u8_ns */
static void
_backup_orc_splat_u8_ns (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int8_t var24 = ex->params[24];

  for (i = 0; i < ex->n; i++) {
    /* 0: copyb */
    var0[i] = var24;
  }

}

void
orc_splat_u8_ns (uint8_t * d1, int p1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_splat_u8_ns");
      orc_program_set_backup_function (p, _backup_orc_splat_u8_ns);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_parameter (p, 1, "p1");

      orc_program_append (p, "copyb", ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  orc_executor_run (ex);
}

/* orc_average_u8 */
static void
_backup_orc_average_u8 (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int8_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];

  for (i = 0; i < ex->n; i++) {
    /* 0: avgub */
    var0[i] = ((uint8_t)var4[i] + (uint8_t)var5[i] + 1)>>1;
  }

}

void
orc_average_u8 (uint8_t * d1, uint8_t * s1, uint8_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_average_u8");
      orc_program_set_backup_function (p, _backup_orc_average_u8);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_source (p, 1, "s2");

      orc_program_append (p, "avgub", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_rrshift6_s16_ip */
static void
_backup_orc_rrshift6_s16_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var16 = 8160;
  const int16_t var17 = 6;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: subw */
    var32 = var0[i] - var16;
    /* 1: shrsw */
    var0[i] = var32 >> var17;
  }

}

void
orc_rrshift6_s16_ip (int16_t * d1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_rrshift6_s16_ip");
      orc_program_set_backup_function (p, _backup_orc_rrshift6_s16_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_constant (p, 2, 8160, "c1");
      orc_program_add_constant (p, 2, 6, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;

  orc_executor_run (ex);
}

/* orc_unpack_yuyv_y */
static void
_backup_orc_unpack_yuyv_y (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: select0wb */
    var0[i] = (uint16_t)var4[i] & 0xff;
  }

}

void
orc_unpack_yuyv_y (uint8_t * d1, uint16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_y");
      orc_program_set_backup_function (p, _backup_orc_unpack_yuyv_y);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "select0wb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_unpack_yuyv_u */
static void
_backup_orc_unpack_yuyv_u (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int32_t * var4 = ex->arrays[4];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: select0lw */
    var32 = (uint32_t)var4[i] & 0xffff;
    /* 1: select1wb */
    var0[i] = ((uint16_t)var32 >> 8)&0xff;
  }

}

void
orc_unpack_yuyv_u (uint8_t * d1, uint32_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_u");
      orc_program_set_backup_function (p, _backup_orc_unpack_yuyv_u);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "select0lw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_unpack_yuyv_v */
static void
_backup_orc_unpack_yuyv_v (OrcExecutor *ex)
{
  int i;
  int8_t * var0 = ex->arrays[0];
  const int32_t * var4 = ex->arrays[4];
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: select1lw */
    var32 = ((uint32_t)var4[i] >> 16)&0xffff;
    /* 1: select1wb */
    var0[i] = ((uint16_t)var32 >> 8)&0xff;
  }

}

void
orc_unpack_yuyv_v (uint8_t * d1, uint32_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_v");
      orc_program_set_backup_function (p, _backup_orc_unpack_yuyv_v);
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "select1lw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_packyuyv */
static void
_backup_orc_packyuyv (OrcExecutor *ex)
{
  int i;
  int32_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];
  const int8_t * var6 = ex->arrays[6];
  int8_t var32;
  int8_t var33;
  int16_t var34;
  int16_t var35;
  int16_t var36;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var36 = var4[i];
    /* 1: select0wb */
    var32 = (uint16_t)var36 & 0xff;
    /* 2: select1wb */
    var33 = ((uint16_t)var36 >> 8)&0xff;
    /* 3: mergebw */
    var34 = ((uint8_t)var32) | ((uint8_t)var5[i] << 8);
    /* 4: mergebw */
    var35 = ((uint8_t)var33) | ((uint8_t)var6[i] << 8);
    /* 5: mergewl */
    var0[i] = ((uint16_t)var34) | ((uint16_t)var35 << 16);
  }

}

void
orc_packyuyv (uint32_t * d1, uint8_t * s1, uint8_t * s2, uint8_t * s3, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_packyuyv");
      orc_program_set_backup_function (p, _backup_orc_packyuyv);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_source (p, 1, "s3");
      orc_program_add_temporary (p, 1, "t1");
      orc_program_add_temporary (p, 1, "t2");
      orc_program_add_temporary (p, 2, "t3");
      orc_program_add_temporary (p, 2, "t4");
      orc_program_add_temporary (p, 2, "t5");

      orc_program_append (p, "copyw", ORC_VAR_T5, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select0wb", ORC_VAR_T1, ORC_VAR_T5, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_T2, ORC_VAR_T5, ORC_VAR_D1);
      orc_program_append (p, "mergebw", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_S2);
      orc_program_append (p, "mergebw", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_S3);
      orc_program_append (p, "mergewl", ORC_VAR_D1, ORC_VAR_T3, ORC_VAR_T4);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;

  orc_executor_run (ex);
}

/* orc_interleave2_s16 */
static void
_backup_orc_interleave2_s16 (OrcExecutor *ex)
{
  int i;
  int32_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];

  for (i = 0; i < ex->n; i++) {
    /* 0: mergewl */
    var0[i] = ((uint16_t)var4[i]) | ((uint16_t)var5[i] << 16);
  }

}

void
orc_interleave2_s16 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_interleave2_s16");
      orc_program_set_backup_function (p, _backup_orc_interleave2_s16);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "mergewl", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_interleave2_rrshift1_s16 */
static void
_backup_orc_interleave2_rrshift1_s16 (OrcExecutor *ex)
{
  int i;
  int32_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t * var5 = ex->arrays[5];
  const int16_t var16 = 1;
  const int16_t var17 = 1;
  const int16_t var18 = 1;
  const int16_t var19 = 1;
  int16_t var32;
  int16_t var33;
  int16_t var34;
  int16_t var35;

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var32 = var4[i] + var16;
    /* 1: shrsw */
    var34 = var32 >> var17;
    /* 2: addw */
    var33 = var5[i] + var18;
    /* 3: shrsw */
    var35 = var33 >> var19;
    /* 4: mergewl */
    var0[i] = ((uint16_t)var34) | ((uint16_t)var35 << 16);
  }

}

void
orc_interleave2_rrshift1_s16 (int16_t * d1, int16_t * s1, int16_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_interleave2_rrshift1_s16");
      orc_program_set_backup_function (p, _backup_orc_interleave2_rrshift1_s16);
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_constant (p, 2, 1, "c1");
      orc_program_add_constant (p, 2, 1, "c2");
      orc_program_add_constant (p, 2, 1, "c3");
      orc_program_add_constant (p, 2, 1, "c4");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2);
      orc_program_append (p, "addw", ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_C3);
      orc_program_append (p, "shrsw", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_C4);
      orc_program_append (p, "mergewl", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
}

/* orc_deinterleave2_s16 */
static void
_backup_orc_deinterleave2_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  int16_t * var1 = ex->arrays[1];
  const int32_t * var4 = ex->arrays[4];
  int32_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyl */
    var32 = var4[i];
    /* 1: select0lw */
    var0[i] = (uint32_t)var32 & 0xffff;
    /* 2: select1lw */
    var1[i] = ((uint32_t)var32 >> 16)&0xffff;
  }

}

void
orc_deinterleave2_s16 (int16_t * d1, int16_t * d2, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_deinterleave2_s16");
      orc_program_set_backup_function (p, _backup_orc_deinterleave2_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_temporary (p, 4, "t1");

      orc_program_append (p, "copyl", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select0lw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "select1lw", ORC_VAR_D2, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_deinterleave2_lshift1_s16 */
static void
_backup_orc_deinterleave2_lshift1_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  int16_t * var1 = ex->arrays[1];
  const int32_t * var4 = ex->arrays[4];
  const int16_t var16 = 1;
  const int16_t var17 = 1;
  int32_t var32;
  int16_t var33;
  int16_t var34;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyl */
    var32 = var4[i];
    /* 1: select0lw */
    var33 = (uint32_t)var32 & 0xffff;
    /* 2: shlw */
    var0[i] = var33 << var16;
    /* 3: select1lw */
    var34 = ((uint32_t)var32 >> 16)&0xffff;
    /* 4: shlw */
    var1[i] = var34 << var17;
  }

}

void
orc_deinterleave2_lshift1_s16 (int16_t * d1, int16_t * d2, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_deinterleave2_lshift1_s16");
      orc_program_set_backup_function (p, _backup_orc_deinterleave2_lshift1_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_constant (p, 2, 1, "c1");
      orc_program_add_constant (p, 2, 1, "c2");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 2, "t3");

      orc_program_append (p, "copyl", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select0lw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_T2, ORC_VAR_C1);
      orc_program_append (p, "select1lw", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shlw", ORC_VAR_D2, ORC_VAR_T3, ORC_VAR_C2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_haar_sub_s16 */
static void
_backup_orc_haar_sub_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: subw */
    var0[i] = var0[i] - var4[i];
  }

}

void
orc_haar_sub_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_sub_s16");
      orc_program_set_backup_function (p, _backup_orc_haar_sub_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_S1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_haar_add_half_s16 */
static void
_backup_orc_haar_add_half_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 0;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: avgsw */
    var32 = (var4[i] + var16 + 1)>>1;
    /* 1: addw */
    var0[i] = var0[i] + var32;
  }

}

void
orc_haar_add_half_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_add_half_s16");
      orc_program_set_backup_function (p, _backup_orc_haar_add_half_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 0, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_haar_add_s16 */
static void
_backup_orc_haar_add_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];

  for (i = 0; i < ex->n; i++) {
    /* 0: addw */
    var0[i] = var0[i] + var4[i];
  }

}

void
orc_haar_add_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_add_s16");
      orc_program_set_backup_function (p, _backup_orc_haar_add_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_S1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_haar_sub_half_s16 */
static void
_backup_orc_haar_sub_half_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 0;
  int16_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: avgsw */
    var32 = (var4[i] + var16 + 1)>>1;
    /* 1: subw */
    var0[i] = var0[i] - var32;
  }

}

void
orc_haar_sub_half_s16 (int16_t * d1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_sub_half_s16");
      orc_program_set_backup_function (p, _backup_orc_haar_sub_half_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 0, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
}

/* orc_sum_u8 */
static void
_backup_orc_sum_u8 (OrcExecutor *ex)
{
  int i;
  const int8_t * var4 = ex->arrays[4];
  int32_t var12 = 0;
  int16_t var32;
  int32_t var33;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var4[i];
    /* 1: convuwl */
    var33 = (uint16_t)var32;
    /* 2: accl */
    var12 = var12 + var33;
  ex->accumulators[0] = var12;
  }

}

void
orc_sum_u8 (int32_t * a1, uint8_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_u8");
      orc_program_set_backup_function (p, _backup_orc_sum_u8);
      orc_program_add_source (p, 1, "s1");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_ds (p, "convubw", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "convuwl", ORC_VAR_T2, ORC_VAR_T1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}

/* orc_sum_s16 */
static void
_backup_orc_sum_s16 (OrcExecutor *ex)
{
  int i;
  const int16_t * var4 = ex->arrays[4];
  int32_t var12 = 0;
  int32_t var32;

  for (i = 0; i < ex->n; i++) {
    /* 0: convswl */
    var32 = var4[i];
    /* 1: accl */
    var12 = var12 + var32;
  ex->accumulators[0] = var12;
  }

}

void
orc_sum_s16 (int32_t * a1, int16_t * s1, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_s16");
      orc_program_set_backup_function (p, _backup_orc_sum_s16);
      orc_program_add_source (p, 2, "s1");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 4, "t1");

      orc_program_append_ds (p, "convswl", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;

  orc_executor_run (ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}

/* orc_sum_square_diff_u8 */
static void
_backup_orc_sum_square_diff_u8 (OrcExecutor *ex)
{
  int i;
  const int8_t * var4 = ex->arrays[4];
  const int8_t * var5 = ex->arrays[5];
  int32_t var12 = 0;
  int16_t var32;
  int16_t var33;
  int32_t var34;
  int16_t var35;
  int16_t var36;

  for (i = 0; i < ex->n; i++) {
    /* 0: convubw */
    var32 = (uint8_t)var4[i];
    /* 1: convubw */
    var33 = (uint8_t)var5[i];
    /* 2: subw */
    var35 = var32 - var33;
    /* 3: mullw */
    var36 = (var35 * var35) & 0xffff;
    /* 4: convuwl */
    var34 = (uint16_t)var36;
    /* 5: accl */
    var12 = var12 + var34;
  ex->accumulators[0] = var12;
  }

}

void
orc_sum_square_diff_u8 (int32_t * a1, uint8_t * s1, uint8_t * s2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_square_diff_u8");
      orc_program_set_backup_function (p, _backup_orc_sum_square_diff_u8);
      orc_program_add_source (p, 1, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");

      orc_program_append_ds (p, "convubw", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "convubw", ORC_VAR_T2, ORC_VAR_S2);
      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T1);
      orc_program_append_ds (p, "convuwl", ORC_VAR_T3, ORC_VAR_T1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T3);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  orc_executor_run (ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}

/* orc_dequantise_s16_ip */
static void
_backup_orc_dequantise_s16_ip (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int16_t var34;
  int16_t var35;
  int16_t var36;
  int16_t var37;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var0[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var34 = ORC_ABS(var32);
    /* 3: mullw */
    var35 = (var34 * var24) & 0xffff;
    /* 4: addw */
    var36 = var35 + var25;
    /* 5: shrsw */
    var37 = var36 >> var16;
    /* 6: mullw */
    var0[i] = (var37 * var33) & 0xffff;
  }

}

void
orc_dequantise_s16_ip (int16_t * d1, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_dequantise_s16_ip");
      orc_program_set_backup_function (p, _backup_orc_dequantise_s16_ip);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P2);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_dequantise_s16 */
static void
_backup_orc_dequantise_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int16_t var34;
  int16_t var35;
  int16_t var36;
  int16_t var37;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var4[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var34 = ORC_ABS(var32);
    /* 3: mullw */
    var35 = (var34 * var24) & 0xffff;
    /* 4: addw */
    var36 = var35 + var25;
    /* 5: shrsw */
    var37 = var36 >> var16;
    /* 6: mullw */
    var0[i] = (var37 * var33) & 0xffff;
  }

}

void
orc_dequantise_s16 (int16_t * d1, int16_t * s1, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_dequantise_s16");
      orc_program_set_backup_function (p, _backup_orc_dequantise_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P2);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_quantise1_s16 */
static void
_backup_orc_quantise1_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  const int16_t var26 = ex->params[26];
  int16_t var32;
  int16_t var33;
  int16_t var34;
  int16_t var35;
  int16_t var36;
  int16_t var37;
  int16_t var38;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var4[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var34 = ORC_ABS(var32);
    /* 3: shlw */
    var35 = var34 << var16;
    /* 4: subw */
    var36 = var35 - var25;
    /* 5: mulhuw */
    var37 = (var36 * var24) >> 16;
    /* 6: shruw */
    var38 = var37 >> var26;
    /* 7: mullw */
    var0[i] = (var38 * var33) & 0xffff;
  }

}

void
orc_quantise1_s16 (int16_t * d1, int16_t * s1, int p1, int p2, int p3, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_quantise1_s16");
      orc_program_set_backup_function (p, _backup_orc_quantise1_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_parameter (p, 2, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shlw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P2);
      orc_program_append (p, "mulhuw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "shruw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P3);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  orc_executor_run (ex);
}

/* orc_quantise2_s16 */
static void
_backup_orc_quantise2_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t * var4 = ex->arrays[4];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int16_t var34;
  int16_t var35;
  int16_t var36;
  int16_t var37;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var4[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var34 = ORC_ABS(var32);
    /* 3: shlw */
    var35 = var34 << var16;
    /* 4: subw */
    var36 = var35 - var25;
    /* 5: shruw */
    var37 = var36 >> var24;
    /* 6: mullw */
    var0[i] = (var37 * var33) & 0xffff;
  }

}

void
orc_quantise2_s16 (int16_t * d1, int16_t * s1, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_quantise2_s16");
      orc_program_set_backup_function (p, _backup_orc_quantise2_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shlw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P2);
      orc_program_append (p, "shruw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}

/* orc_quantise1_large_s16 */
static void
_backup_orc_quantise1_large_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  const int16_t var26 = ex->params[26];
  int16_t var32;
  int16_t var33;
  int32_t var34;
  int16_t var35;
  int32_t var36;
  int32_t var37;
  int32_t var38;
  int32_t var39;
  int16_t var40;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var0[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var35 = ORC_ABS(var32);
    /* 3: convuwl */
    var34 = (uint16_t)var35;
    /* 4: shll */
    var36 = var34 << var16;
    /* 5: subl */
    var37 = var36 - var25;
    /* 6: mulhul */
    var38 = ((uint64_t)var37 * (uint64_t)var24) >> 32;
    /* 7: shrul */
    var39 = ((uint32_t)var38) >> var26;
    /* 8: convlw */
    var40 = var39;
    /* 9: mullw */
    var0[i] = (var40 * var33) & 0xffff;
  }

}

void
orc_quantise1_large_s16 (int16_t * d1, int p1, int p2, int p3, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_quantise1_large_s16");
      orc_program_set_backup_function (p, _backup_orc_quantise1_large_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_parameter (p, 2, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "convuwl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shll", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_C1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "mulhul", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "shrul", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P3);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  orc_executor_run (ex);
}

/* orc_quantise2_large_s16 */
static void
_backup_orc_quantise2_large_s16 (OrcExecutor *ex)
{
  int i;
  int16_t * var0 = ex->arrays[0];
  const int16_t var16 = 2;
  const int16_t var24 = ex->params[24];
  const int16_t var25 = ex->params[25];
  int16_t var32;
  int16_t var33;
  int32_t var34;
  int16_t var35;
  int32_t var36;
  int32_t var37;
  int32_t var38;
  int16_t var39;

  for (i = 0; i < ex->n; i++) {
    /* 0: copyw */
    var32 = var0[i];
    /* 1: signw */
    var33 = ORC_CLAMP(var32,-1,1);
    /* 2: absw */
    var35 = ORC_ABS(var32);
    /* 3: convuwl */
    var34 = (uint16_t)var35;
    /* 4: shll */
    var36 = var34 << var16;
    /* 5: subl */
    var37 = var36 - var25;
    /* 6: shrul */
    var38 = ((uint32_t)var37) >> var24;
    /* 7: convlw */
    var39 = var38;
    /* 8: mullw */
    var0[i] = (var39 * var33) & 0xffff;
  }

}

void
orc_quantise2_large_s16 (int16_t * d1, int p1, int p2, int n)
{
  static int p_inited = 0;
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (!p_inited) {
    MUTEX_LOCK ();
    if (!p_inited) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_quantise2_large_s16");
      orc_program_set_backup_function (p, _backup_orc_quantise2_large_s16);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");

      orc_program_append (p, "copyw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append (p, "signw", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "absw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "convuwl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append (p, "shll", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_C1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "shrul", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort ();
      }
    }
    p_inited = TRUE;
    MUTEX_UNLOCK ();
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  orc_executor_run (ex);
}
