
/* autogenerated from schro.orc */

#include <orc/orc.h>
#include <stdio.h>
#include <stdlib.h>
#include <schroedinger/schro.h>
#define MUTEX_LOCK schro_mutex_lock (orc_mutex);
#define MUTEX_UNLOCK schro_mutex_unlock (orc_mutex);
SchroMutex *orc_mutex;

#ifndef MUTEX_LOCK
#define MUTEX_LOCK
#endif
#ifndef MUTEX_UNLOCK
#define MUTEX_UNLOCK
#endif



/* orc_add2_rshift_add_s16_22 */
void
orc_add2_rshift_add_s16_22 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_add_s16_22");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_constant (p, 2, 2, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add2_rshift_sub_s16_22 */
void
orc_add2_rshift_sub_s16_22 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_sub_s16_22");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_constant (p, 2, 2, "c1");
      orc_program_add_constant (p, 2, 2, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add2_rshift_add_s16_11 */
void
orc_add2_rshift_add_s16_11 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_add_s16_11");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add2_rshift_sub_s16_11 */
void
orc_add2_rshift_sub_s16_11 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add2_rshift_sub_s16_11");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add_const_rshift_s16_11 */
void
orc_add_const_rshift_s16_11 (int16_t *d1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_const_rshift_s16_11");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 1, "c1");
      orc_program_add_constant (p, 2, 1, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add_const_rshift_s16 */
void
orc_add_const_rshift_s16 (int16_t *d1, int p1, int p2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_const_rshift_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 2, "p2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_P1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_P2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add_s16 */
void
orc_add_s16 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_addc_rshift_s16 */
void
orc_addc_rshift_s16 (int16_t *d1, int16_t *s1, int16_t *s2, int p1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_addc_rshift_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_P1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_lshift1_s16 */
void
orc_lshift1_s16 (int16_t *d1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift1_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 1, "c1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_lshift2_s16 */
void
orc_lshift2_s16 (int16_t *d1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift2_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 2, "c1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_lshift_s16_ip */
void
orc_lshift_s16_ip (int16_t *d1, int p1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_lshift_s16_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");

      orc_program_append (p, "shlw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_P1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_mas2_add_s16_ip */
void
orc_mas2_add_s16_ip (int16_t *d1, int16_t *s1, int16_t *s2, int p1, int p2, int p3, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas2_add_s16_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_parameter (p, 4, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "mulswl", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P2);
      orc_program_append (p, "shrsl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P3);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_mas2_sub_s16_ip */
void
orc_mas2_sub_s16_ip (int16_t *d1, int16_t *s1, int16_t *s2, int p1, int p2, int p3, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas2_sub_s16_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_parameter (p, 2, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_parameter (p, 4, "p3");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_S2);
      orc_program_append (p, "mulswl", ORC_VAR_T2, ORC_VAR_T1, ORC_VAR_P1);
      orc_program_append (p, "addl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P2);
      orc_program_append (p, "shrsl", ORC_VAR_T2, ORC_VAR_T2, ORC_VAR_P3);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;
  ex->params[ORC_VAR_P3] = p3;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_mas4_across_add_s16_1991_ip */
void
orc_mas4_across_add_s16_1991_ip (int16_t *d1, int16_t *s1, int16_t *s2, int16_t *s3, int16_t *s4, int p1, int p2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas4_across_add_s16_1991_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_source (p, 2, "s3");
      orc_program_add_source (p, 2, "s4");
      orc_program_add_constant (p, 2, 9, "c1");
      orc_program_add_parameter (p, 4, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");
      orc_program_add_temporary (p, 4, "t4");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_S3);
      orc_program_append (p, "mulswl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_T2, ORC_VAR_S1, ORC_VAR_S4);
      orc_program_append (p, "convswl", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_T4);
      orc_program_append (p, "addl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "shrsl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;
  ex->arrays[ORC_VAR_S4] = s4;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_mas4_across_sub_s16_1991_ip */
void
orc_mas4_across_sub_s16_1991_ip (int16_t *d1, int16_t *s1, int16_t *s2, int16_t *s3, int16_t *s4, int p1, int p2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_mas4_across_sub_s16_1991_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");
      orc_program_add_source (p, 2, "s3");
      orc_program_add_source (p, 2, "s4");
      orc_program_add_constant (p, 2, 9, "c1");
      orc_program_add_parameter (p, 4, "p1");
      orc_program_add_parameter (p, 4, "p2");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");
      orc_program_add_temporary (p, 4, "t4");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_S3);
      orc_program_append (p, "mulswl", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_T2, ORC_VAR_S1, ORC_VAR_S4);
      orc_program_append (p, "convswl", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append (p, "subl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_T4);
      orc_program_append (p, "addl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P1);
      orc_program_append (p, "shrsl", ORC_VAR_T3, ORC_VAR_T3, ORC_VAR_P2);
      orc_program_append (p, "convlw", ORC_VAR_T1, ORC_VAR_T3, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;
  ex->arrays[ORC_VAR_S4] = s4;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_subtract_s16 */
void
orc_subtract_s16 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_subtract_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_memcpy */
void
orc_memcpy (void *d1, void *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_memcpy");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 1, "s1");

      orc_program_append (p, "copyb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_add_s16_u8 */
void
orc_add_s16_u8 (int16_t *d1, int16_t *s1, uint8_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_add_s16_u8");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_S1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_convert_s16_u8 */
void
orc_convert_s16_u8 (uint16_t *d1, uint8_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_convert_s16_u8");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 1, "s1");

      orc_program_append (p, "convubw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_convert_u8_s16 */
void
orc_convert_u8_s16 (uint8_t *d1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_convert_u8_s16");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "convsuswb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_offsetconvert_u8_s16 */
void
orc_offsetconvert_u8_s16 (uint8_t *d1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_offsetconvert_u8_s16");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_constant (p, 2, 128, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "addw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_C1);
      orc_program_append (p, "convsuswb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_offsetconvert_s16_u8 */
void
orc_offsetconvert_s16_u8 (int16_t *d1, uint8_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_offsetconvert_s16_u8");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_constant (p, 2, 128, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_subtract_s16_u8 */
void
orc_subtract_s16_u8 (int16_t *d1, int16_t *s1, uint8_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_subtract_s16_u8");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_multiply_and_add_s16_u8 */
void
orc_multiply_and_add_s16_u8 (int16_t *d1, int16_t *s1, uint8_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_multiply_and_add_s16_u8");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "convubw", ORC_VAR_T1, ORC_VAR_S2, ORC_VAR_D1);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_splat_s16_ns */
void
orc_splat_s16_ns (int16_t *d1, int p1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_splat_s16_ns");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_parameter (p, 2, "p1");

      orc_program_append (p, "copyw", ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_splat_u8_ns */
void
orc_splat_u8_ns (uint8_t *d1, int p1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_splat_u8_ns");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_parameter (p, 1, "p1");

      orc_program_append (p, "copyb", ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_average_u8 */
void
orc_average_u8 (uint8_t *d1, uint8_t *s1, uint8_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_average_u8");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_source (p, 1, "s2");

      orc_program_append (p, "avgub", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_rrshift6_s16_ip */
void
orc_rrshift6_s16_ip (int16_t *d1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_rrshift6_s16_ip");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_constant (p, 2, 8160, "c1");
      orc_program_add_constant (p, 2, 6, "c2");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_D1, ORC_VAR_C1);
      orc_program_append (p, "shrsw", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_C2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_unpack_yuyv_y */
void
orc_unpack_yuyv_y (uint8_t *d1, uint16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_y");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 2, "s1");

      orc_program_append (p, "select0wb", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_unpack_yuyv_u */
void
orc_unpack_yuyv_u (uint8_t *d1, uint32_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_u");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "select0lw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_unpack_yuyv_v */
void
orc_unpack_yuyv_v (uint8_t *d1, uint32_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_unpack_yuyv_v");
      orc_program_add_destination (p, 1, "d1");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "select1lw", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_packyuyv */
void
orc_packyuyv (uint32_t *d1, uint8_t *s1, uint8_t *s2, uint8_t *s3, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_packyuyv");
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_source (p, 1, "s3");
      orc_program_add_temporary (p, 1, "t1");
      orc_program_add_temporary (p, 1, "t2");
      orc_program_add_temporary (p, 2, "t3");
      orc_program_add_temporary (p, 2, "t4");

      orc_program_append (p, "select0wb", ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1wb", ORC_VAR_T2, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "mergebw", ORC_VAR_T3, ORC_VAR_T1, ORC_VAR_S2);
      orc_program_append (p, "mergebw", ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_S3);
      orc_program_append (p, "mergewl", ORC_VAR_D1, ORC_VAR_T3, ORC_VAR_T4);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;
  ex->arrays[ORC_VAR_S3] = s3;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_interleave2_s16 */
void
orc_interleave2_s16 (int16_t *d1, int16_t *s1, int16_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_interleave2_s16");
      orc_program_add_destination (p, 4, "d1");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_source (p, 2, "s2");

      orc_program_append (p, "mergewl", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_S2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_deinterleave2_s16 */
void
orc_deinterleave2_s16 (int16_t *d1, int16_t *d2, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_deinterleave2_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_source (p, 4, "s1");

      orc_program_append (p, "select0lw", ORC_VAR_D1, ORC_VAR_S1, ORC_VAR_D1);
      orc_program_append (p, "select1lw", ORC_VAR_D2, ORC_VAR_S1, ORC_VAR_D1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_haar_sub_s16 */
void
orc_haar_sub_s16 (int16_t *d1, int16_t *d2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_sub_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");

      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_D2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_haar_add_half_s16 */
void
orc_haar_add_half_s16 (int16_t *d1, int16_t *d2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_add_half_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_constant (p, 2, 0, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_D2, ORC_VAR_C1);
      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_haar_add_s16 */
void
orc_haar_add_s16 (int16_t *d1, int16_t *d2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_add_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");

      orc_program_append (p, "addw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_D2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_haar_sub_half_s16 */
void
orc_haar_sub_half_s16 (int16_t *d1, int16_t *d2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_haar_sub_half_s16");
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_constant (p, 2, 0, "c1");
      orc_program_add_temporary (p, 2, "t1");

      orc_program_append (p, "avgsw", ORC_VAR_T1, ORC_VAR_D2, ORC_VAR_C1);
      orc_program_append (p, "subw", ORC_VAR_D1, ORC_VAR_D1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_D2] = d2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
}


/* orc_sum_u8 */
void
orc_sum_u8 (int32_t *a1, uint8_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_u8");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 4, "t2");

      orc_program_append_ds (p, "convubw", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "convuwl", ORC_VAR_T2, ORC_VAR_T1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T2);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}


/* orc_sum_s16 */
void
orc_sum_s16 (int32_t *a1, int16_t *s1, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_s16");
      orc_program_add_source (p, 2, "s1");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 4, "t1");

      orc_program_append_ds (p, "convuwl", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T1);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}


/* orc_sum_square_diff_u8 */
void
orc_sum_square_diff_u8 (int32_t *a1, uint8_t *s1, uint8_t *s2, int n)
{
  static OrcProgram *p = NULL;
  OrcExecutor _ex, *ex = &_ex;

  if (p == NULL) {
    MUTEX_LOCK
    if (p == NULL) {
      OrcCompileResult result;

      p = orc_program_new ();
      orc_program_set_name (p, "orc_sum_square_diff_u8");
      orc_program_add_source (p, 1, "s1");
      orc_program_add_source (p, 1, "s2");
      orc_program_add_accumulator (p, 4, "a1");
      orc_program_add_temporary (p, 2, "t1");
      orc_program_add_temporary (p, 2, "t2");
      orc_program_add_temporary (p, 4, "t3");

      orc_program_append_ds (p, "convubw", ORC_VAR_T1, ORC_VAR_S1);
      orc_program_append_ds (p, "convubw", ORC_VAR_T2, ORC_VAR_S2);
      orc_program_append (p, "subw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2);
      orc_program_append (p, "mullw", ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T1);
      orc_program_append_ds (p, "convuwl", ORC_VAR_T3, ORC_VAR_T1);
      orc_program_append_ds (p, "accl", ORC_VAR_A1, ORC_VAR_T3);

      result = orc_program_compile (p);
      if (!ORC_COMPILE_RESULT_IS_SUCCESSFUL (result)) {
        abort();
      }
    }
    MUTEX_UNLOCK
  }

  ex->program = p;
  ex->n = n;
  ex->arrays[ORC_VAR_S1] = s1;
  ex->arrays[ORC_VAR_S2] = s2;

  ((void (*)(OrcExecutor *))ex->program->code_exec)(ex);
  *a1 = orc_executor_get_accumulator (ex, ORC_VAR_A1);
}

