#!/bin/sh


set -x

rm -rf tmp-build-dir
mkdir tmp-build-dir

cd tmp-build-dir &&
  svn co https://core.fluendo.com/carid/svn/trunk/schroedinger/ &&
  cd schroedinger &&
  ./autogen.sh &&
  make &&
  make distcheck &&
  cd ../.. &&
  rm -rf tmp-build-dir &&
  echo SUCCESS!




