#!/bin/sh

../decode /dev/null

opcontrol --image=all
opcontrol --init
opcontrol --reset
opcontrol -e default
opcontrol --start
opcontrol --status
../decode ~/dirac-720p25-5Mbps.drc
opcontrol --stop
opreport -l -t 0.1 >report
opcontrol --shutdown

