#!/bin/bash


GST_LAUNCH=$(type -p gst-launch-0.10)
if test "$GST_LAUNCH" = "" ; then
  echo This test requires GStreamer
fi

if test ! -f /usr/lib/libprofiler.so -o ! -f /usr/bin/pprof ; then
  echo This test requires the Google profiler tools.
  exit 1
fi

schroopts="mv-precision=1"

CPUPROFILE=prof.out \
LD_PRELOAD=/usr/lib/libprofiler.so \
$GST_LAUNCH \
	filesrc location=~/media/masters/sage.HD720-master.drc ! \
	schrodec ! \
	schroenc $schroopts ! filesink location=out.drc

pprof --pdf $GST_LAUNCH prof.out >prof.pdf


