#!/bin/sh


function encode {
  gst-launch-0.10 \
    videotestsrc num-buffers=300 ! \
    video/x-raw-yuv,format=\(fourcc\)"$format",width=$width,height=$height,framerate=30/1 ! \
    timeoverlay ! \
    cairotextoverlay text=$testname halign=left deltay=-100 ! \
    schroenc $schroopts ! \
    filesink location=vts.$testname.drc
}


width=352
height=240
format=I420


testname="intra-only"
schroopts="engine=0"
encode

testname="backref"
schroopts="engine=1"
encode

# broken
#testname="backref2"
#schroopts="engine=2"
#encode

testname="tworef"
schroopts="engine=3"
encode

testname="test_intra"
schroopts="engine=4"
encode

# broken playback
#testname="lossless"
#schroopts="engine=5"
#encode

# broken playback
#testname="backtest"
#schroopts="engine=6"
#encode

testname=lowdelay
bitrate=$(($width*$height*3/2*8*30))
schroopts="engine=7 transform_depth=3 bitrate=$(($bitrate/4))"
encode

