
#ifndef __SCHRO_OPENGL_SHADER_H__
#define __SCHRO_OPENGL_SHADER_H__

#include <schroedinger/schro.h>
#include <schroedinger/opengl/schroopengl.h>

SCHRO_BEGIN_DECLS

typedef struct _SchroOpenGLShader SchroOpenGLShader;

struct _SchroOpenGLShader {
  GLhandleARB program;
  GLint textures[3];
  GLint offset;
  GLint one;
};

#define SCHRO_OPENGL_SHADER_IDENTITY             0
#define SCHRO_OPENGL_SHADER_CONVERT_U8_S16       1
#define SCHRO_OPENGL_SHADER_CONVERT_S16_U8       2
#define SCHRO_OPENGL_SHADER_CONVERT_U8_U8        3
#define SCHRO_OPENGL_SHADER_CONVERT_S16_S16      4
#define SCHRO_OPENGL_SHADER_CONVERT_U8_Y4_YUYV   5
#define SCHRO_OPENGL_SHADER_CONVERT_U8_U2_YUYV   6
#define SCHRO_OPENGL_SHADER_CONVERT_U8_V2_YUYV   7
#define SCHRO_OPENGL_SHADER_CONVERT_U8_Y4_UYVY   8
#define SCHRO_OPENGL_SHADER_CONVERT_U8_U2_UYVY   9
#define SCHRO_OPENGL_SHADER_CONVERT_U8_V2_UYVY  10
#define SCHRO_OPENGL_SHADER_CONVERT_U8_Y4_AYUV  11
#define SCHRO_OPENGL_SHADER_CONVERT_U8_U4_AYUV  12
#define SCHRO_OPENGL_SHADER_CONVERT_U8_V4_AYUV  13
#define SCHRO_OPENGL_SHADER_CONVERT_YUYV_U8_422 14
#define SCHRO_OPENGL_SHADER_CONVERT_UYVY_U8_422 15
#define SCHRO_OPENGL_SHADER_CONVERT_AYUV_U8_444 16
#define SCHRO_OPENGL_SHADER_ADD_S16_U8          17
#define SCHRO_OPENGL_SHADER_ADD_S16_S16         18
#define SCHRO_OPENGL_SHADER_SUBTRACT_S16_U8     19
#define SCHRO_OPENGL_SHADER_SUBTRACT_S16_S16    20
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_DEINTERLEAVE_XL         21
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_DEINTERLEAVE_XH         22
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_FILTER_LE_GALL_5_3_XLp  23
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_FILTER_LE_GALL_5_3_XHp  24
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_FILTER_HAAR_XLp         25
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_FILTER_HAAR_XHp         26
#define SCHRO_OPENGL_SHADER_IIWT_S16_VERTICAL_INTERLEAVE              27
#define SCHRO_OPENGL_SHADER_IIWT_S16_HORIZONTAL_FILTER_LE_GALL_5_3_Lp 28
#define SCHRO_OPENGL_SHADER_IIWT_S16_HORIZONTAL_FILTER_LE_GALL_5_3_Hp 29
#define SCHRO_OPENGL_SHADER_IIWT_S16_HORIZONTAL_FILTER_HAAR_Lp        30
#define SCHRO_OPENGL_SHADER_IIWT_S16_HORIZONTAL_FILTER_HAAR_Hp        31
#define SCHRO_OPENGL_SHADER_IIWT_S16_HORIZONTAL_INTERLEAVE            32
#define SCHRO_OPENGL_SHADER_IIWT_S16_FILTER_SHIFT                     33

#define SCHRO_OPENGL_SHADER_COUNT SCHRO_OPENGL_SHADER_IIWT_S16_FILTER_SHIFT

SchroOpenGLShaderLibrary *schro_opengl_shader_library_new (SchroOpenGL *opengl);
void schro_opengl_shader_library_free (SchroOpenGLShaderLibrary *library);
SchroOpenGLShader *schro_opengl_shader_get (SchroOpenGL *opengl, int index);

SCHRO_END_DECLS

#endif

