#!/bin/sh

#export GST_DEBUG=dirac:5

encode() {
  echo "ENCODING $testname with $diracopts"
  gst-launch-0.10 \
    videotestsrc num-buffers=150 ! \
    timeoverlay ! \
    cairotextoverlay text=$testname halign=left deltay=-100 ! \
    ffmpegcolorspace ! \
    video/x-raw-yuv,format=\(fourcc\)"$format",width=$width,height=$height,framerate=30/1 ! \
    diracenc $diracopts ! \
    filesink location=vts.dirac-$testname.drc
}


width=320
height=240
format=I420

#testname="CBR-2Mb"
#diracopts="targetrate=2000"
#encode
#exit

testname="default"
diracopts=""
encode

# gop structure

testname="intra-only"
diracopts="num-l1=0"
encode

#testname="backref"
#diracopts="gop-structure=2"
#encode

#testname="biref"
#diracopts="gop-structure=4"
#encode

# rate control

testname="CBR-250kb"
diracopts="targetrate=250"
encode

testname="CBR-500kb"
diracopts="targetrate=500"
encode

testname="CBR-1Mb"
diracopts="targetrate=1000"
encode

testname="CBR-2Mb"
diracopts="targetrate=2000"
encode

testname="lossless"
diracopts="lossless=true"
encode

# qf

testname="qf-1.0"
diracopts="qf=1.0"
encode

testname="qf-3.0"
diracopts="qf=3.0"
encode

testname="qf-5.0"
diracopts="qf=5.0"
encode

testname="qf-7.0"
diracopts="qf=7.0"
encode

testname="qf-9.0"
diracopts="qf=9.0"
encode

# filtering

#testname="denoise"
#diracopts="denoise=true"
#encode

# transform depth

testname="transform-1"
diracopts="wlt-depth=1"
encode

testname="transform-2"
diracopts="wlt-depth=2"
encode

testname="transform-3"
diracopts="wlt-depth=3"
encode

testname="transform-4"
diracopts="wlt-depth=4"
encode

# intra wavelet

for i in 0 1 2 3 4 5 6 ; do
  testname="intra-wavelet-$i"
  diracopts="num-l1=0 iwlt-filter=$i"
  encode
done

for i in 0 1 2 3 4 5 6 ; do
  testname="inter-wavelet-$i"
  diracopts="rwlt-filter=$i"
  encode
done
 
for i in 0 1 2 3 ; do
  testname="mv-precision-$i"
  diracopts="mv-prec=$i"
  encode
done

for j in 8 12 16 ; do
  testname="MB-8x8-${j}x${j}"
  diracopts="xbsep=8 ybsep=8 xblen=$j yblen=$j"
  encode
done

for j in 12 16 24 ; do
  testname="MB-12x12-${j}x${j}"
  diracopts="xbsep=12 ybsep=12 xblen=$j yblen=$j"
  encode
done

for j in 16 20 24 ; do
  testname="MB-16x16-${j}x${j}"
  diracopts="xbsep=16 ybsep=16 xblen=$j yblen=$j"
  encode
done


