#!/bin/sh

test -f /home/ds/output.ogg && rm /home/ds/output.ogg

gst-launch-0.10 \
  dvdreadsrc title="3" ! \
  decodebin name="dvd" dvd. ! \
  ffmpegcolorspace ! \
  schroenc ! \
  queue ! \
  oggmux name=mux ! \
  gnomevfssink location=file:///home/cschalle/output.ogg dvd. ! \
  audioconvert ! \
  vorbisenc ! \
  queue ! \
  mux.

