#!/bin/sh

if [ "$(whoami)" = "ds" ] ; then
  title=1
elif [ "$(whoami)" = "cschalle" ] ; then
  title=5
else
  title=5
fi

gst-launch-0.10 \
  dvdreadsrc title="$title" ! \
  decodebin name="dvd" dvd. ! \
  ffmpegcolorspace ! \
  videorate ! \
    video/x-raw-yuv,framerate=12/1 ! \
  schroenc ! \
  queue ! \
  oggmux name=mux ! \
  filesink location=output.ogg dvd. ! \
  audioconvert ! \
  vorbisenc ! \
  queue ! \
  mux.

#  videoscale method=1 ! \
#    video/x-raw-yuv,width=352,height=288,pixel-aspect-ratio=\(fraction\)16/15 ! \
