#!/bin/sh

if [ "$(whoami)" = "ds" ] ; then
  title=1
elif [ "$(whoami)" = "cschalle" ] ; then
  title=5
else
  title=5
fi


#valgrind \
#gdb -args \
gst-launch-0.10 \
  dvdreadsrc title="$title" ! \
  flupsdemux name="dvd" \
  dvd. ! \
    mpeg2dec ! \
    ffmpegcolorspace ! \
    videorate ! \
    video/x-raw-yuv,framerate=24/1 ! \
    schroenc ! \
    queue ! \
  oggmux name=mux ! \
  filesink location=output.ogg \
  dvd. ! \
    a52dec ! \
    audioconvert ! \
    vorbisenc ! \
    queue ! \
    mux.

#  videoscale method=1 ! \
#    video/x-raw-yuv,width=352,height=288,pixel-aspect-ratio=\(fraction\)16/15 ! \
