#!/bin/sh

gst-launch-0.10 \
  dvdreadsrc title="5" ! \
  decodebin name="dvd" dvd. ! \
  ffmpegcolorspace ! \
  video/x-raw-yuv,format=\(fourcc\)YUY2 ! \
  videoscale method=1 ! \
  video/x-raw-yuv,format=\(fourcc\)YUY2,width=360,height=288,pixel-aspect-ratio=\(fraction\)16/15 ! \
  videorate ! \
  video/x-raw-yuv,framerate=25/2 ! \
  ffmpegcolorspace ! \
  caridenc ! \
  queue ! \
  oggmux name=mux ! \
  gnomevfssink location=file:///home/cschalle/villanova5.ogg dvd. ! \
  audioconvert ! \
  vorbisenc ! \
  queue ! \
  mux

