#!/bin/sh

mediadir=/home/ds/media

all="SD-default SD-VBR-10dB SD-VBR-20dB SD-VBR-30dB SD-VBR-40dB \
    SD-CBR-250kb SD-CBR-500kb SD-CBR-1Mb SD-CBR-2Mb \
    SD-LD-40Mb SD-LD-10Mb SD-lossless SD-intra-only"

list="$all"

list=SD-2Mb

#extraopts="enable-phasecorr-prediction=true enable-hierarchical-prediction=false"

trap exit INT

function get_profile {
  case $1 in
    SD-default) schroopts="" ;;
    SD-10dB) schroopts="rate-control=0 noise-threshold=10" ;;
    SD-20dB) schroopts="rate-control=0 noise-threshold=20" ;;
    SD-30dB) schroopts="rate-control=0 noise-threshold=30" ;;
    SD-40dB) schroopts="rate-control=0 noise-threshold=40" ;;
    SD-250kb) schroopts="rate-control=1 bitrate=250000" ;;
    SD-500kb) schroopts="rate-control=1 bitrate=500000" ;;
    SD-1Mb) schroopts="rate-control=1 bitrate=1000000" ;;
    SD-2Mb) schroopts="rate-control=1 bitrate=2000000" ;;
    SD-LD-40Mb) schroopts="rate-control=2 bitrate=41472000" ;;
    SD-LD-20Mb) schroopts="rate-control=2 bitrate=20736000" ;;
    SD-LD-10Mb) schroopts="rate-control=2 bitrate=10368000" ;;
    SD-lossless) schroopts="rate-control=3" ;;
    SD-intra-only) schroopts="gop-structure=1" ;;
  esac
}

function encode {
  # engine3
  get_profile $prof
  output=$file.$prof.drc
  echo "encoding $file using $prof"

  gst-launch-0.10 multifilesrc location=$subdir/%05d.uyvy \
    caps="video/x-raw-yuv,format=\(fourcc\)UYVY,width=1920,height=1080,framerate=$framerate,pixel-aspect-ratio=$par" ! \
    videoscale ! \
    video/x-raw-yuv,width=960,height=540 ! \
    ffmpegcolorspace ! \
    schroenc $schroopts $extraopts ! \
    filesink location=$output >/dev/null 2>/dev/null
}

function encode_all {
  for each in $list
  do
    prof=$each
    encode
  done
}



#subdir=/media/bbc-diracreal/dirac-longgop-showreel-20071129
subdir=/mnt/wallace/home/ds/bbc/dirac-longgop-showreel-20071129
height=1920
width=1080
par=1/1
framerate=25/1

file=showreel
encode_all

