#!/bin/sh

gst-launch-0.10 filesrc location=/home/ds/media/spider-man-tsr_dfs2.mov \
  ! decodebin ! caridenc ! cariddec ! xvimagesink sync=false

#gst-launch-0.10 filesrc location=/home/ds/media/pianostripper5.mpg \
#  ! decodebin ! caridenc ! cariddec ! xvimagesink

